# SwiftLint configuration for Pipflow

# Paths to include
included:
  - Pipflow

# Paths to exclude
excluded:
  - Pipflow.xcodeproj
  - .build
  - Packages
  - PipflowTests
  - PipflowUITests

# Rules configuration
opt_in_rules:
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

disabled_rules:
  - todo
  - trailing_whitespace
  - line_length

# Rule configuration
file_length:
  warning: 500
  error: 600
  
type_body_length:
  warning: 300
  error: 400
  
function_body_length:
  warning: 50
  error: 100
  
function_parameter_count:
  warning: 6
  error: 8
  
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60
    
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - to
    - or
    - x
    - y
    - z
    
large_tuple:
  warning: 3
  error: 4
  
cyclomatic_complexity:
  warning: 10
  error: 20
  
nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Custom rules
custom_rules:
  mark_comment:
    name: "MARK Comment"
    regex: '//\s*MARK:\s*-\s*\w+'
    message: "MARK comments should have proper format: // MARK: - Section Name"
    severity: warning
    
  todo_fixme:
    name: "TODO/FIXME"
    regex: '(TODO|FIXME):'
    message: "TODOs and FIXMEs should be resolved before production"
    severity: warning
    
  print_usage:
    name: "Print Usage"
    regex: '\bprint\('
    message: "print() should not be used in production code. Use proper logging instead."
    severity: warning
    
  force_cast:
    name: "Force Cast"
    regex: 'as!\s'
    message: "Avoid force casting. Use conditional casting instead."
    severity: error

# Reporter type
reporter: "xcode"