name: iOS CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Pipflow/**'
      - '.github/workflows/ios-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'Pipflow/**'

env:
  XCODE_VERSION: '15.1'
  IOS_SIMULATOR: 'iPhone 15 Pro'
  IOS_VERSION: '17.2'

jobs:
  code-quality:
    name: Code Quality & Linting
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
      
    - name: Cache SwiftLint
      uses: actions/cache@v4
      with:
        path: ~/.swiftlint
        key: ${{ runner.os }}-swiftlint-${{ hashFiles('Pipflow/.swiftlint.yml') }}
        
    - name: Install SwiftLint
      run: |
        if ! command -v swiftlint &> /dev/null; then
          brew install swiftlint
        fi
        
    - name: Run SwiftLint
      run: |
        cd Pipflow
        swiftlint lint --reporter github-actions-logging

  build-test:
    name: Build & Test iOS App
    runs-on: macos-14
    needs: code-quality
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
      
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          Pipflow/.build
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('Pipflow/Package.swift') }}
        
    - name: Build iOS App
      run: |
        cd Pipflow
        xcodebuild build \
          -scheme Pipflow \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
          CODE_SIGNING_ALLOWED=NO
